import neo4j, {type Driver} from 'neo4j-driver';
import { items, traits, recipes, configVersion, zero, type Stats } from '../shared/config';
import type { Session } from './engine';
export class GraphRepository {
  driver:Driver|null=null; status='disabled';
  constructor(){if(process.env.NEO4J_URI&&process.env.NEO4J_PASSWORD){this.driver=neo4j.driver(process.env.NEO4J_URI,neo4j.auth.basic(process.env.NEO4J_USERNAME||'neo4j',process.env.NEO4J_PASSWORD),{connectionTimeout:3000,maxTransactionRetryTime:2000});this.status='pending';}}
  async init(){if(!this.driver)return;try{await this.driver.verifyConnectivity();const db=this.driver.session({database:process.env.NEO4J_DATABASE||'neo4j'});try{
    for(const label of ['Session','Participant','Contribution','Item','Trait','Recipe','RecipeUnlock','MutationEvent','EvolutionCandidate','Vote','Monster','GenerationRun','Outcome','ActionChoice','Trial'])await db.run(`CREATE CONSTRAINT ${label.toLowerCase()}_id IF NOT EXISTS FOR (n:${label}) REQUIRE n.id IS UNIQUE`);
    for(const item of items){await db.run('MERGE (i:Item {id:$id}) SET i.itemId=$itemId, i.name=$name', {id:`${configVersion}:${item.id}`,itemId:item.id,name:item.name.en});for(const [trait,value]of Object.entries(item.weights))await db.run('MATCH (i:Item {id:$item}) MERGE (t:Trait {id:$id}) SET t.traitId=$trait MERGE (i)-[r:SHIFTS]->(t) SET r.value=$value',{item:`${configVersion}:${item.id}`,id:`${configVersion}:${trait}`,trait,value});}
    for(const recipe of recipes)await db.run('MERGE (r:Recipe {id:$id}) SET r.recipeId=$recipeId WITH r UNWIND $items AS item MATCH (i:Item {id:item}) MERGE (r)-[q:REQUIRES]->(i) SET q.perAssignee=20',{id:`${configVersion}:${recipe.id}`,recipeId:recipe.id,items:recipe.required.map(i=>`${configVersion}:${i}`)});
    this.status='ready';
  }finally{await db.close();}}catch{this.status='pending';}}
  async save(s:Session){if(!this.driver)return;const db=this.driver.session({database:process.env.NEO4J_DATABASE||'neo4j'});try{await db.executeWrite(async tx=>{
    await tx.run('MERGE (s:Session {id:$id}) SET s.phase=$phase,s.configVersion=$config,s.version=$version', {id:s.id,phase:s.phase,config:s.configVersion,version:s.version});
    const rows=Object.values(s.people).map(p=>({id:p.id,tokenHash:p.tokenHash,name:p.displayName.en,shareId:p.shareId,contributionId:`${s.id}:${p.id}:round-1`,item:`${s.configVersion}:${p.itemId}`,count:p.acceptedTotal,seq:p.lastSeq,total:p.lastClientTotal,result:p.result?JSON.stringify(p.result):''}));
    await tx.run(`MATCH (s:Session {id:$sid}) UNWIND $rows AS row MERGE (p:Participant {id:row.id}) SET p.sessionId=$sid,p.tokenHash=row.tokenHash,p.name=row.name,p.shareId=row.shareId,p.resultJson=row.result MERGE (p)-[:JOINED]->(s) MERGE (c:Contribution {id:row.contributionId}) SET c.sessionId=$sid,c.acceptedCount=row.count,c.lastSeq=row.seq,c.lastClientTotal=row.total MERGE (p)-[:MADE]->(c) MERGE (c)-[:IN_SESSION]->(s) WITH row,c MATCH (i:Item {id:row.item}) MERGE (c)-[:OF_ITEM]->(i)`,{sid:s.id,rows});
    for(const c of s.candidates){await tx.run('MATCH (s:Session {id:$sid}) MERGE (c:EvolutionCandidate {id:$id}) SET c.name=$name,c.specJson=$json MERGE (s)-[:HAS_CANDIDATE]->(c)',{sid:s.id,id:c.id,name:c.name.en,json:JSON.stringify(c)});
      for(const i of c.sourceItemIds)await tx.run('MATCH (c:EvolutionCandidate {id:$c}),(i:Item {id:$i}) MERGE (c)-[:DERIVED_FROM]->(i)',{c:c.id,i:`${s.configVersion}:${i}`});
      for(const t of traits.filter(t=>s.raw[t]>0))await tx.run('MATCH (c:EvolutionCandidate {id:$c}),(t:Trait {id:$t}) MERGE (c)-[r:EXPRESSES]->(t) SET r.rawScore=$score',{c:c.id,t:`${s.configVersion}:${t}`,score:s.raw[t]});
      if(c.recipeId){const rid=`${s.id}:${c.recipeId}`,required=recipes.find(r=>r.id===c.recipeId)!.required;await tx.run('MATCH (s:Session {id:$s}),(r:Recipe {id:$r}),(c:EvolutionCandidate {id:$c}) MERGE (u:RecipeUnlock {id:$id}) MERGE (s)-[:HAS_UNLOCK]->(u) MERGE (u)-[:OF_RECIPE]->(r) MERGE (u)-[:ENABLED]->(c)',{s:s.id,r:`${s.configVersion}:${c.recipeId}`,c:c.id,id:rid});for(const p of Object.values(s.people).filter(p=>p.acceptedTotal&&required.includes(p.itemId)))await tx.run('MATCH (c:Contribution {id:$c}),(u:RecipeUnlock {id:$u}) MERGE (c)-[r:SUPPORTED]->(u) SET r.count=$count,r.share=$share',{c:`${s.id}:${p.id}:round-1`,u:rid,count:p.acceptedTotal,share:p.acceptedTotal/s.totals[p.itemId]});}
    }
    for(const m of s.mutations){await tx.run('MATCH (p:Participant {id:$p}),(s:Session {id:$s}) MERGE (m:MutationEvent {id:$id}) SET m.evidenceJson=$json MERGE (p)-[:TRIGGERED]->(m) MERGE (m)-[:IN_SESSION]->(s)',{p:m.participantId,s:s.id,id:m.id,json:JSON.stringify(m)});for(const c of s.candidates.filter(c=>c.mutations.some(x=>x.id===m.id)))await tx.run('MATCH (m:MutationEvent {id:$m}),(c:EvolutionCandidate {id:$c}) MERGE (m)-[:ADOPTED_BY]->(c)',{m:m.id,c:c.id});}
    if(s.candidates.length)await tx.run('MATCH (s:Session {id:$s}) MERGE (g:GenerationRun {id:$id}) SET g.logJson=$json MERGE (s)-[:HAS_GENERATION]->(g) WITH s,g MATCH (s)-[:HAS_CANDIDATE]->(c) MERGE (g)-[:RENDERS]->(c)',{s:s.id,id:s.generationKey,json:JSON.stringify(s.generationLog)});
    if(s.winner){await tx.run('MATCH (s:Session {id:$s}),(c:EvolutionCandidate {id:$c}) MERGE (m:Monster {id:$id}) MERGE (s)-[:BIRTHED]->(m) MERGE (m)-[:BASED_ON]->(c)',{s:s.id,c:s.winner.id,id:`${s.id}:monster`});if(s.enableTrial){await tx.run('MATCH (m:Monster {id:$m}) MERGE (t:Trial {id:$t}) MERGE (m)-[:FACED]->(t)',{m:`${s.id}:monster`,t:`${s.id}:trial`});for(const a of ['break','persuade','ritual'])await tx.run('MATCH (t:Trial {id:$t}) MERGE (a:ActionChoice {id:$a}) SET a.actionKey=$key MERGE (t)-[:HAS_ACTION]->(a)',{t:`${s.id}:trial`,a:`${s.id}:${a}`,key:a});}}
    for(const p of Object.values(s.people))for(const kind of ['evolution','trial'] as const){const target=kind==='evolution'?p.evolutionVote:p.trialVote?`${s.id}:${p.trialVote}`:null;if(target)await tx.run(`MATCH (p:Participant {id:$p}),(target:${kind==='evolution'?'EvolutionCandidate':'ActionChoice'} {id:$target}) MERGE (v:Vote {id:$id}) SET v.kind=$kind MERGE (p)-[:CAST]->(v) MERGE (v)-[:FOR]->(target)`,{p:p.id,target,id:`${s.id}:${p.id}:${kind}`,kind});}
    if(s.outcome)await tx.run('MATCH (t:Trial {id:$t}),(a:ActionChoice {id:$a}) MERGE (o:Outcome {id:$id}) SET o.resultJson=$json MERGE (t)-[:RESOLVED_AS]->(o) MERGE (a)-[:LED_TO]->(o)',{t:`${s.id}:trial`,a:`${s.id}:${s.outcome.actionId}`,id:`${s.id}:outcome`,json:JSON.stringify(s.outcome)});
  });this.status='ready';}catch(e){this.status='pending';throw e;}finally{await db.close();}}
  async facts(sid:string):Promise<Stats>{if(!this.driver)throw Error('disabled');const result=await this.driver.executeQuery('MATCH (c:Contribution {sessionId:$sid})-[:OF_ITEM]->(i:Item)-[r:SHIFTS]->(t:Trait) RETURN t.traitId AS trait,sum(c.acceptedCount*r.value) AS points',{sid},{database:process.env.NEO4J_DATABASE||'neo4j'});const stats=zero();for(const r of result.records)stats[r.get('trait') as keyof Stats]=Number(r.get('points'));return stats;}
  async personalFacts(sid:string,pid:string){if(!this.driver)return [];const r=await this.driver.executeQuery('MATCH (p:Participant {id:$pid})-[:MADE]->(c:Contribution {sessionId:$sid})-[:OF_ITEM]->(i:Item)-[shift:SHIFTS]->(t:Trait) MATCH (s:Session {id:$sid})-[:BIRTHED]->(:Monster)-[:BASED_ON]->(e:EvolutionCandidate)-[:EXPRESSES]->(t) WHERE c.acceptedCount > 0 RETURN t.traitId AS trait,c.acceptedCount*shift.value AS points',{sid,pid},{database:process.env.NEO4J_DATABASE||'neo4j'});return r.records.map(row=>({trait:row.get('trait') as keyof Stats,points:Number(row.get('points'))}));}
}
