import test from 'node:test';
import assert from 'node:assert/strict';
import {aggregate,applyTap,createSession,join,makeCandidates,publicState,resolveTrial,results,selectWinner,start,tick,transition,unlocked,vote} from '../src/server/engine';
import {items,traits} from '../src/shared/config';
import {copy,errors} from '../src/web/i18n';
function fixture(){const s=createSession(true,0),p=join(s).person;p.itemId='fire';start(s,0);tick(s,5000);return{s,p};}
test('balanced 50-player roles and hard join limit',()=>{const s=createSession();for(let i=0;i<50;i++)join(s);const counts=items.map(i=>Object.values(s.people).filter(p=>p.itemId===i.id).length);assert.ok(Math.max(...counts)-Math.min(...counts)<=1);assert.throws(()=>join(s),/SESSION_FULL/);});
test('tap retry and out-of-order delivery do not add or lose counts',()=>{const{s,p}=fixture();const r={roundId:'round-1',seq:7,clientTotal:43};applyTap(s,p,r,12000);applyTap(s,p,r,12000);assert.equal(p.acceptedTotal,43);applyTap(s,p,{...r,seq:8,clientTotal:50},13000);applyTap(s,p,r,14000);assert.equal(p.acceptedTotal,50);assert.equal(s.totals.fire,50);assert.throws(()=>applyTap(s,p,{...r,seq:8,clientTotal:51},14000),/SEQUENCE_CONFLICT/);});
test('excess is consumed once, never resurrected on retry',()=>{const{s,p}=fixture();applyTap(s,p,{roundId:'round-1',seq:1,clientTotal:1000},6000);assert.equal(p.acceptedTotal,16);applyTap(s,p,{roundId:'round-1',seq:2,clientTotal:1000},15000);assert.equal(p.acceptedTotal,16);applyTap(s,p,{roundId:'round-1',seq:3,clientTotal:1001},15000);assert.equal(p.acceptedTotal,17);});
test('drain cutoff is exclusive; invalid counts are rejected',()=>{const{s,p}=fixture();tick(s,20000);applyTap(s,p,{roundId:'round-1',seq:1,clientTotal:10},20999);assert.equal(p.acceptedTotal,10);assert.throws(()=>applyTap(s,p,{roundId:'round-1',seq:2,clientTotal:20},21000),/PHASE_CLOSED/);assert.throws(()=>applyTap(s,p,{roundId:'round-1',seq:2,clientTotal:NaN},21000),/INVALID_TOTAL/);});
test('threshold stores the exact accepted ordinal within a batch',()=>{const{s,p}=fixture();s.totals.fire=23;p.acceptedTotal=10;p.lastClientTotal=10;applyTap(s,p,{roundId:'round-1',seq:1,clientTotal:20},12000);assert.equal(s.mutations.length,1);assert.equal(s.mutations[0].ordinal,17);applyTap(s,p,{roundId:'round-1',seq:2,clientTotal:25},14000);assert.equal(s.mutations.length,1);});
test('material effects and all-zero worlds are well-defined',()=>{const{s,p}=fixture();applyTap(s,p,{roundId:'round-1',seq:1,clientTotal:43},12000);aggregate(s);assert.equal(s.raw.chaos,86);assert.equal(s.raw.heat,86);assert.equal(s.raw.aggression,43);const empty=createSession();makeCandidates(empty);assert.equal(empty.candidates.length,3);assert.equal(empty.alignment,0);assert.ok(traits.every(t=>Number.isFinite(empty.stats[t])));});
test('recipes require existing roles and belong to their session',()=>{const s=createSession(),p=join(s).person,q=join(s).person;p.itemId='fire';q.itemId='knowledge';s.totals.fire=20;s.totals.knowledge=20;assert.equal(unlocked(s)[0].id,'ember_archive');makeCandidates(s);assert.equal(s.candidates[1].kind,'secret');const another=createSession();assert.equal(unlocked(another).length,0);});
test('candidate identities and names are deterministic',()=>{const{s}=fixture();s.totals.fire=40;const clone=structuredClone(s);makeCandidates(s);makeCandidates(clone);assert.deepEqual(s.candidates,clone.candidates);assert.equal(s.candidates[1].kind,'alternative');});
test('votes are immutable, idempotent, phase checked, and tied by saved order',()=>{const{s,p}=fixture();makeCandidates(s);transition(s,'EVOLUTION_VOTE',0);vote(s,p,'evolution',s.candidates[0].id,100);vote(s,p,'evolution',s.candidates[0].id,200);assert.throws(()=>vote(s,p,'evolution',s.candidates[1].id,300),/VOTE_LOCKED/);selectWinner(s);assert.equal(s.winner!.id,s.candidates[0].id);const empty=createSession();makeCandidates(empty);selectWinner(empty);assert.equal(empty.winner!.id.slice(-1),empty.tieOrder[0]);});
test('every phase reaches a final personal result with or without trial',()=>{for(const enableTrial of [true,false]){const s=createSession(enableTrial,0),p=join(s).person;start(s,0);tick(s,5000);applyTap(s,p,{roundId:'round-1',seq:1,clientTotal:43},12000);tick(s,20000);tick(s,21000);makeCandidates(s);s.generationDone=true;tick(s,33000);tick(s,45000);vote(s,p,'evolution',s.candidates[0].id,46000);tick(s,65000);tick(s,73000);if(enableTrial){vote(s,p,'trial','ritual',74000);tick(s,93000);tick(s,105000);}assert.equal(s.phase,'RESULTS');assert.equal(p.result!.count,43);assert.equal(p.result!.evolutionWon,true);assert.equal(!!s.outcome,enableTrial);}});
test('no contribution invents a mutation; the public state carries no tokens',()=>{const{s,p}=fixture();makeCandidates(s);selectWinner(s);resolveTrial(s);results(s);assert.equal(p.result!.mutations.length,0);assert.equal(p.result!.title.en,'Witness of a Beginning');const json=JSON.stringify(publicState(s,'http://localhost'));assert.ok(!json.includes(p.tokenHash));assert.ok(!json.includes(p.id));});
test('50-player simulation keeps per-person points equal to room totals',()=>{const s=createSession(),people=Array.from({length:50},()=>join(s).person);start(s,0);tick(s,5000);for(let batch=1;batch<=20;batch++)for(const p of people)applyTap(s,p,{roundId:'round-1',seq:batch,clientTotal:batch*4},5000+batch*500);aggregate(s);assert.equal(Object.values(s.totals).reduce((a,b)=>a+b,0),4000);makeCandidates(s);selectWinner(s);results(s);for(const t of traits)assert.equal(people.reduce((sum,p)=>sum+p.result!.points[t],0),s.raw[t]);});
test('all UI dictionary entries have nonempty EN and JP content',()=>{for(const dictionary of [copy,errors])for(const [key,value]of Object.entries(dictionary)){assert.ok(value.en.trim(),`${key}.en`);assert.ok(value.ja.trim(),`${key}.ja`);assert.ok(!/[\u3040-\u30ff\u4e00-\u9fff]/.test(value.en),`${key} English contains Japanese`);}});
