import {Daytona} from '@daytona/sdk';
import {readFileSync,writeFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
process.loadEnvFile('.env');
const apiOrigin=process.argv[2];
if(!apiOrigin||new URL(apiOrigin).protocol!=='https:')throw Error('Pass the HTTPS origin of the running Mac API.');
if(!process.env.DAYTONA_SANDBOX_ID)throw Error('Select the existing approved sandbox.');
if(!process.argv.includes('--skip-build'))execFileSync('npm',['run','build'],{stdio:'inherit',env:{...process.env,VITE_API_ORIGIN:apiOrigin}});
const sandbox=await new Daytona({apiKey:process.env.DAYTONA_API_KEY}).get(process.env.DAYTONA_SANDBOX_ID);
if(sandbox.state!=='started')await sandbox.start(60);
const home=await sandbox.getUserHomeDir(),remote=`${home}/crowd-monster`;
execFileSync('tar',['-czf','data/demo-frontend.tar.gz','dist','scripts/frontend.ts']);
await sandbox.fs.uploadFile(readFileSync('data/demo-frontend.tar.gz'),`${remote}/demo-frontend.tar.gz`);
const unpack=await sandbox.process.executeCommand('tar -xzf demo-frontend.tar.gz',remote,undefined,20);
if(unpack.exitCode!==0)throw Error('Frontend upload failed.');
await sandbox.process.executeCommand("pkill -f '[n]ode --import tsx src/server/index.ts' || true; pkill -f '[n]ode --import tsx scripts/frontend.ts' || true",remote,undefined,10);
const sessionId=`hatch-frontend-${Date.now()}`;await sandbox.process.createSession(sessionId);
await sandbox.process.executeSessionCommand(sessionId,{command:`cd '${remote}' && PORT=3000 node --import tsx scripts/frontend.ts`,runAsync:true});
const output={url:(await sandbox.getPreviewLink(3000)).url,apiOrigin,processSession:sessionId,requires:'Keep the Mac API and tunnel running; keep the Mac awake.'};
writeFileSync('data/demo-deployment.json',JSON.stringify(output,null,2));console.log(JSON.stringify(output,null,2));
