import { bi, type Text } from '../shared/config';
export const copy={
  app:bi('HATCH','HATCH'),tag:bi('A little creature. A collective imagination.','小さな生き物。みんなの想像力。'),
  homeTitle:bi('What will we become?','どんな未来に、育てよう。'),homeBody:bi('Feed a little mystery, uncover three possible futures, and choose one together.','なぞの生き物に素材を送り、3つの未来から、みんなでひとつを選ぼう。'),
  create:bi('Create a room','ルームを作る'),joinRoom:bi('Join a room','ルームに参加'),roomLink:bi('Room link or ID','ルームのURLまたはID'),play:bi('Play on this device','この端末で参加'),stage:bi('Open big screen','大画面を開く'),host:bi('Host controls','ホスト操作'),back:bi('Back to the nest','ホームに戻る'),
  live:bi('A SHARED LITTLE EXPERIMENT','みんなで育てる小さな実験'),players:bi('keepers','人の育て手'),feeds:bi('ingredients given','回の投与'),waiting:bi('Waiting to hatch','誕生を待っています'),lobbyBody:bi('Scan the code. Find your ingredient. Make something unexpected together.','QRを読み取り、担当素材を受け取ろう。みんなで、予想外の何かを。'),scan:bi('Scan to join','QRで参加'),copyLink:bi('Copy invite link','招待リンクをコピー'),copied:bi('Copied!','コピーしました'),start:bi('Start the experiment','育成をはじめる'),newRoom:bi('Create another room','新しいルームを作る'),
  hostKey:bi('Host key','ホストキー'),unlock:bi('Unlock controls','操作を有効にする'),hostHint:bi('Use the key configured on the server. Local access connects automatically.','サーバーに設定したキーを入力。ローカルアクセスは自動接続します。'),trial:bi('Include the final adventure','最後の試練を含める'),stop:bi('End this session','このセッションを中断'),fallback:bi('Reveal with fallback artwork','代替画像で公開する'),
  join:bi('Give me an ingredient','担当素材を受け取る'),yourRole:bi('YOUR INGREDIENT','あなたの担当素材'),waitHost:bi('Your ingredient is ready. The host will begin shortly.','準備ができました。ホストが開始するまで待とう。'),getReady:bi('Ready, little world?','さあ、準備はいい？'),feedTitle:bi('A future in every tap.','ひと押しが、未来になる。'),tap:bi('Tap to feed','タップして与える'),accepted:bi('received','反映済み'),pending:bi('sending','送信待ち'),rest:bi('A little pause. Extra-fast taps do not count.','ひと休み。速すぎる分は数えられません。'),lastBatch:bi('Counting the last few ingredients…','最後の素材を集計中…'),
  generating:bi('Three futures are taking shape.','3つの未来が、形になる。'),genBody:bi('Your ingredients are finding unexpected connections.','みんなの素材が、予想外のつながりを見つけています。'),readyImages:bi('live images ready','枚のライブ画像が完成'),reveal:bi('Meet your possible futures.','あり得た未来に、出会おう。'),choose:bi('Which future feels like us?','私たちらしい未来は、どれ？'),voteHelp:bi('One keeper, one vote. Your choice is final.','ひとり一票。投票後は変更できません。'),vote:bi('Choose this future','この未来を選ぶ'),chosen:bi('Your choice','あなたの一票'),voted:bi('Your vote is in. Let the room decide.','投票できました。みんなの選択を待とう。'),votes:bi('votes cast','票が集まりました'),noVote:bi('No vote cast','投票なし'),
  dominant:bi('THE LIKELY ONE','本命の未来'),secret:bi('A SECRET UNLOCKED','秘密の進化'),alternative:bi('ANOTHER POSSIBILITY','もうひとつの解釈'),mutation:bi('THE WILD CARD','突然変異'),illustration:bi('Fallback artwork','代替イラスト'),liveImage:bi('Generated this round','今回生成'),
  born:bi('Hello, little possibility.','はじめまして、小さな可能性。'),bornBody:bi('This is the creature you chose together.','みんなが選んだ、この会場だけの生き物。'),noVotesBirth:bi('No votes were cast. The saved draw order chose this future.','投票がなかったため、保存済みの抽選順で決まりました。'),
  trialTitle:bi('One last door to open.','最後に、ひとつの門。'),trialBody:bi('A closed gate stands between your creature and a new world. What should it try?','新しい世界へ続く門が閉ざされています。この子は、どう進む？'),actionVote:bi('Choose this action','この行動を選ぶ'),outcome:bi('And so, a new story begins.','そして、新しい物語が始まる。'),
  result:bi('Made by all of us.','みんなで、生まれた。'),resultBody:bi('One shared creature. A different story for every keeper.','同じ生き物。でも、育て手の物語はひとりずつ違う。'),yourStory:bi('Your part in the story','あなたが紡いだ物語'),gave:bi('YOU GAVE','あなたが与えたもの'),chose:bi('YOU CHOSE','あなたが選んだ未来'),influence:bi('YOUR INFLUENCE','あなたが与えた影響'),title:bi('YOUR TITLE','あなたの称号'),chosenWon:bi('Your future was chosen.','あなたの未来が選ばれました。'),chosenLost:bi('You stood for another possible future.','あなたは、別の可能性を支えました。'),actionMatched:bi('The room chose your action.','みんなも、あなたと同じ行動を選びました。'),actionDifferent:bi('The room took a different path.','みんなは、別の道を選びました。'),
  share:bi('Share your story','物語を共有'),shareText:bi('Copy story + link','共有文とURLをコピー'),shareX:bi('Share on X','Xで共有'),publicNotice:bi('Anyone with this link can view your card.','リンクを知っている人は、このカードを閲覧できます。'),savePending:bi('Saving your keepsake…','持ち帰りカードを保存中…'),graph:bi('Contribution path','貢献のつながり'),graphVerified:bi('Verified from the graph','グラフで確認済み'),
  interrupted:bi('This little experiment has ended.','この育成は中断されました。'),interruptedBody:bi('Ask the host for a new room link to begin again.','ホストから新しいルームのURLを受け取ってください。'),spectator:bi('You are watching this round.','今回は観戦しています。'),spectatorBody:bi('Joining closes when the countdown starts. You can join the next round.','カウントダウンで参加受付は終了。次の回に参加できます。'),loading:bi('Finding the nest…','ルームに接続中…'),connecting:bi('Reconnecting… your received ingredients are safe.','再接続中…反映済みの素材は保持されています。'),seconds:bi('sec','秒'),room:bi('ROOM','ルーム'),quickFacts:bi('5–50 keepers · about 3 minutes · no account','5〜50人 · 約3分 · アカウント不要'),
  ingredients:bi('Six ingredients. Infinite little possibilities.','6つの素材から、無数の小さな可能性。'),allIngredients:bi('THE ROOM’S INGREDIENTS','会場から届いた素材'),chooseRole:bi('A role for every keeper','ひとりひとりに役割を'),choiceMissing:bi('Your vote was not sent. Try again before the timer ends.','投票を送信できませんでした。締切までに再送してください。'),
  configuration:bi('Connections','接続'),disabled:bi('Not connected','未接続'),configured:bi('Configured, unverified','設定済み・未検証'),ready:bi('Connected','接続済み'),localFallback:bi('Illustrated fallback mode','代替イラストモード'),pendingStatus:bi('Waiting for connection','接続待ち'),
  errors:bi('Something went wrong. Please try again.','処理できませんでした。もう一度お試しください。')
} satisfies Record<string,Text>;
export const errors:Record<string,Text>={
  UNAUTHORIZED:bi('Your session key is missing or expired. Reconnect with your saved key.','キーがないか無効です。保存したキーで再接続してください。'),HOST_KEY_REQUIRED:bi('Enter the host key to open these controls.','操作するにはホストキーを入力してください。'),NOT_FOUND:bi('This room or result could not be found.','このルームまたは結果は見つかりません。'),JOIN_CLOSED:bi('This round has started. Join the next one.','この回は始まりました。次の回に参加してください。'),SESSION_FULL:bi('This room already has 50 keepers.','このルームは50人で満員です。'),SESSION_ACTIVE:bi('A room is already running. Open it below.','進行中のルームがあります。下から開いてください。'),START_REQUIRES_PLAYERS:bi('At least one keeper must join before starting.','開始には1人以上の参加が必要です。'),PHASE_CLOSED:bi('That part of the game has ended.','この操作の受付は終了しました。'),SEQUENCE_CONFLICT:bi('Another tab may be sending taps. Reload this tab to sync.','別のタブで操作中かもしれません。再読み込みで同期してください。'),INVALID_TOTAL:bi('That ingredient count could not be accepted.','この素材数は受け付けられません。'),VOTE_LOCKED:bi('Your first vote is already recorded.','最初の一票が記録済みです。'),INVALID_CHOICE:bi('Choose one of the options in this room.','このルームの選択肢から選んでください。'),STALE_PHASE:bi('The game has moved on. Try the control again.','ゲームが進みました。もう一度操作してください。'),COMMAND_CONFLICT:bi('That command was already used for a different action.','この操作IDは別の操作で使われています。'),INVALID_INPUT:bi('Please check the information you entered.','入力内容を確認してください。'),RESULT_NOT_READY:bi('Your story is still unfolding.','物語はまだ続いています。'),RATE_LIMITED:bi('A little too fast. Please wait a moment.','操作が速すぎます。少し待ってください。'),FORBIDDEN:bi('This action is not available here.','ここではこの操作を実行できません。'),SERVER_ERROR:bi('The server could not finish that action. Please retry.','処理を完了できませんでした。再試行してください。'),NETWORK:bi('Connection interrupted. Trying again…','通信が切れました。再接続しています…'),WRONG_ROUND:bi('These ingredients belong to another round.','別のラウンドの素材です。')};
