import React,{useState,useEffect,useRef,createContext,useContext} from 'react';
import {createRoot} from 'react-dom/client';
import QRCode from 'qrcode';
import {actions,bi,items,itemById,traitNames,traits,type Text,type Lang,type ItemId} from '../shared/config';
import type {PublicState,Me,Candidate,PersonalResult} from '../shared/types';
import {copy,errors} from './i18n';
import './style.css';
const Locale=createContext<{lang:Lang;setLang:(l:Lang)=>void}>({lang:'en',setLang:()=>{}});
function useText(){const {lang}=useContext(Locale);return (value:Text)=>value[lang];}
class APIError extends Error {constructor(public code:string){super(code);}}
async function api<T=any>(path:string,body?:unknown,token?:string):Promise<T>{try{const r=await fetch(`/api${path}`,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(8000)});const data=await r.json();if(!r.ok)throw new APIError(data.error?.code||'SERVER_ERROR');return data;}catch(e){if(e instanceof APIError)throw e;throw new APIError('NETWORK');}}
function ErrorNotice({code}:{code:string}){const t=useText();return code?<div className="notice error" role="alert">{t(errors[code]||copy.errors)}</div>:null;}
function Header(){const {lang,setLang}=useContext(Locale),t=useText();return <header className="header"><a className="brand" href="/" aria-label={t(copy.back)}><span className="brand-mark">✳</span> HATCH<span className="brand-dot">.</span></a><div className="header-right"><a className="host-link" href="/host">{t(copy.host)}</a><div className="language" role="tablist" aria-label="Language" onKeyDown={e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){setLang(lang==='en'?'ja':'en');(e.currentTarget.querySelector(`[data-lang="${lang==='en'?'ja':'en'}"]`) as HTMLButtonElement)?.focus();}}}>{(['en','ja']as Lang[]).map(l=><button key={l} data-lang={l} role="tab" aria-selected={lang===l} tabIndex={lang===l?0:-1} className={lang===l?'selected':''} onClick={()=>setLang(l)}>{l==='ja'?'JP':'EN'}</button>)}</div></div></header>;}
function Creature({candidate,egg=false,large=false}:{candidate?:Candidate|null;egg?:boolean;large?:boolean}){const t=useText();return <div className={`creature ${large?'large':''} ${egg?'egg':''}`}><div className="aura"/>{egg?<svg viewBox="0 0 400 400" role="img" aria-label={t(bi('A mysterious egg','なぞのタマゴ'))}><defs><radialGradient id="egg-light" cx="30%" cy="20%" r="85%"><stop stopColor="#e8dcff"/><stop offset=".52" stopColor="#a89adf"/><stop offset="1" stopColor="#51467d"/></radialGradient></defs><ellipse cx="200" cy="332" rx="92" ry="16" fill="#08050f" opacity=".55"/><path d="M200 55C150 55 94 156 94 239c0 64 45 97 106 97s106-33 106-97C306 156 250 55 200 55Z" fill="url(#egg-light)"/><path d="m169 145 24 22-19 20 36 20-8 26 37-17" fill="none" stroke="#f2ffd0" strokeWidth="5" strokeLinecap="round"/><ellipse cx="156" cy="124" rx="15" ry="28" fill="#fff" opacity=".22" transform="rotate(25 156 124)"/><path d="M139 265q19 16 38 0M223 265q19 16 38 0" stroke="#3a2d59" strokeWidth="8" fill="none" strokeLinecap="round"/><ellipse cx="144" cy="286" rx="15" ry="7" fill="#eea5d4" opacity=".5"/><ellipse cx="256" cy="286" rx="15" ry="7" fill="#eea5d4" opacity=".5"/></svg>:<img src={candidate?.imageUrl||'/fallback/A.svg'} alt={candidate?t(candidate.name):t(bi('Creature','生き物'))} onError={e=>{if(!e.currentTarget.dataset.fallback){e.currentTarget.dataset.fallback='1';e.currentTarget.src='/fallback/A.svg';}}}/>}<span className="orbit o1">✧</span><span className="orbit o2">✦</span><span className="orbit o3">·</span></div>;}
function Home(){const t=useText(),[link,setLink]=useState(''),[error,setError]=useState('');function enter(e:React.FormEvent){e.preventDefault();const sid=link.match(/[a-f0-9]{32}/)?.[0];if(sid)location.href=`/play/${sid}`;else setError('INVALID_INPUT');}return <main className="home"><div className="home-copy"><p className="eyebrow">{t(copy.live)}</p><h1>{t(copy.homeTitle)}</h1><p className="intro">{t(copy.homeBody)}</p><div className="home-actions"><a href="/host" className="button primary">{t(copy.create)} <span>↗</span></a></div><form className="join-form" onSubmit={enter}><label htmlFor="room-link">{t(copy.joinRoom)}</label><div><input id="room-link" value={link} onChange={e=>setLink(e.target.value)} placeholder={t(copy.roomLink)} required/><button className="button secondary" type="submit">↗<span className="sr-only">{t(copy.joinRoom)}</span></button></div></form><ErrorNotice code={error}/><p className="meta">{t(copy.quickFacts)}</p></div><div className="home-art"><Creature egg large/><div className="art-caption"><span className="capsule">01 / ∞</span><p>{t(copy.waiting)}</p></div></div><div className="ingredients-ribbon">{items.map(i=><div key={i.id}><span style={{color:i.color}}>{i.icon}</span>{t(i.name)}</div>)}</div></main>;}
function useSession(sid:string,token:string,stage=false){const [state,setState]=useState<PublicState|null>(null),[me,setMe]=useState<Me|null>(null),[error,setError]=useState('');const version=useRef(-1);
  useEffect(()=>{if(!sid){setState(null);setMe(null);return;}let alive=true,timer:ReturnType<typeof setTimeout>;version.current=-1;async function poll(){try{const data=await api<any>(`/sessions/${sid}/${token?'me':'state'}`,undefined,token);const s:PublicState=token?data.state:data;if(alive){if(s.version>=version.current){version.current=s.version;setState(s);if(token)setMe(data);}else setState(prev=>prev?{...prev,serverNow:s.serverNow}:s);setError('');}}catch(e){if(alive)setError((e as APIError).code);}if(alive)timer=setTimeout(poll,document.hidden?3000:stage?250:1000);}void poll();return()=>{alive=false;clearTimeout(timer);};},[sid,token,stage]);return {state,me,error};}
function QR({url}:{url:string}){const [src,setSrc]=useState(''),t=useText();useEffect(()=>{void QRCode.toDataURL(url,{width:240,margin:2,color:{dark:'#211732',light:'#ffffff'}}).then(setSrc);},[url]);return <div className="qr">{src&&<img src={src} alt={t(copy.scan)}/>}<span>{t(copy.scan)}</span></div>;}
function Timer({state}:{state:PublicState}){const [now,setNow]=useState(Date.now()),offset=useRef(0),t=useText();useEffect(()=>{offset.current=state.serverNow-Date.now();},[state.serverNow]);useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),100);return()=>clearInterval(id);},[]);const seconds=Math.max(0,Math.ceil(((state.phaseEndsAt||now)-now-offset.current)/1000));return state.phaseEndsAt?<div className={`timer ${seconds<=5?'urgent':''}`} aria-label={`${seconds} ${t(copy.seconds)}`}><strong>{String(seconds).padStart(2,'0')}</strong><span>{t(copy.seconds)}</span></div>:null;}
function IngredientBar({state}:{state:PublicState}){const t=useText(),max=Math.max(1,...Object.values(state.totals));return <div className="ingredient-bars">{items.map(i=><div key={i.id} className="ingredient-row"><span>{i.icon}</span><span>{t(i.name)}</span><div className="bar-track"><div style={{width:`${100*state.totals[i.id]/max}%`,background:i.color}}/></div><b>{state.totals[i.id]}</b></div>)}</div>;}
function Facts({state}:{state:PublicState}){const t=useText();return <div className="facts"><div><strong>{state.participantCount}</strong><span>{t(copy.players)}</span></div><div><strong>{state.totalAccepted.toLocaleString()}</strong><span>{t(copy.feeds)}</span></div></div>;}
function Stats({candidate}:{candidate:Candidate}){const t=useText();const top=traits.filter(k=>!['law','chaos'].includes(k)).sort((a,b)=>candidate.stats[b]-candidate.stats[a]).slice(0,3);return <div className="stat-pills">{top.map(k=><span key={k}>{t(traitNames[k])}<b>{candidate.stats[k]}</b></span>)}</div>;}
function CandidateCards({state,me,onVote,busy}:{state:PublicState;me:Me|null;onVote?:(id:string)=>void;busy?:boolean}){const t=useText();const visible=state.phase==='REVEAL'?Math.min(3,Math.max(1,1+Math.floor((12000-Math.max(0,(state.phaseEndsAt||0)-state.serverNow))/4000))):3;return <div className="candidate-grid">{state.candidates.map((c,k)=><article className={`candidate-card ${me?.evolutionVote===c.id?'voted':''} ${k>=visible?'reveal-hidden':''}`} aria-hidden={k>=visible} key={c.id}><div className="candidate-label"><span>0{k+1}</span><span>{t(copy[c.kind])}</span></div><Creature candidate={c}/><div className="candidate-text"><h2>{t(c.name)}</h2><p>{t(c.description)}</p><Stats candidate={c}/><span className={`image-source ${c.imageSource==='nosana-live'?'live-image':''}`}>{t(c.imageSource==='nosana-live'?copy.liveImage:copy.illustration)}</span>{onVote&&<button className={`button ${me?.evolutionVote===c.id?'primary':'secondary'}`} disabled={!!me?.evolutionVote||busy} onClick={()=>onVote(c.id)}>{t(me?.evolutionVote===c.id?copy.chosen:copy.vote)}</button>}</div></article>)}</div>;}
function ResultView({state,result}:{state:PublicState;result:PersonalResult|null}){const t=useText(),{lang}=useContext(Locale),[copied,setCopied]=useState(false),[error,setError]=useState('');const winner=state.winner;if(!winner)return null;const shareUrl=result?`${location.origin}/r/${result.shareId}`:`${location.origin}/monster/${state.id}`;const shareText=lang==='en'?`${state.participantCount} keepers raised ${winner.name.en}. ${result?`I gave ${result.count} ${itemById(result.itemId).name.en.toLowerCase()}. ${result.title.en}. LAW +${result.points.law}, CHAOS +${result.points.chaos}. `:''}#CrowdMonster\n${shareUrl}`:`${state.participantCount}人で育てた「${winner.name.ja}」。${result?`${itemById(result.itemId).name.ja}を${result.count}回。称号は「${result.title.ja}」。LAW +${result.points.law}、CHAOS +${result.points.chaos}。`:''} #みんなの怪物\n${shareUrl}`;
  const vote=state.candidates.find(c=>c.id===result?.evolutionVote);return <main className="result-page"><div className="section-heading"><p className="eyebrow">{t(copy.result)}</p><h1>{t(winner.name)}</h1><p>{t(copy.resultBody)}</p></div><div className="result-layout"><div className="result-creature"><Creature candidate={winner} large/><Stats candidate={winner}/><Facts state={state}/><div className="alignment"><span>LAW</span><div><i style={{left:`${(state.alignment+100)/2}%`}}/></div><span>CHAOS</span></div></div><div className="result-content">{state.outcome&&<blockquote><span>✧ {t(copy.outcome)}</span>{t(state.outcome.text)}</blockquote>}{result&&<><div className="personal-title"><p className="eyebrow">{t(copy.title)}</p><h2>{t(result.title)}</h2><p>{t(result.titleReason)}</p></div><div className="personal-grid"><div><label>{t(copy.gave)}</label><strong>{itemById(result.itemId).icon} {result.count} <small>{t(itemById(result.itemId).name)}</small></strong></div><div><label>{t(copy.influence)}</label><strong>+{result.points.chaos} <small>CHAOS</small></strong><span>+{result.points.law} LAW</span></div></div><div className="your-choice"><label>{t(copy.chose)}</label><h3>{vote?t(vote.name):t(copy.noVote)}</h3>{result.evolutionWon!==null&&<p>{t(result.evolutionWon?copy.chosenWon:copy.chosenLost)}</p>}{result.trialVote&&<p>{t(actions.find(a=>a.id===result.trialVote)!.name)} · {t(result.trialMatched?copy.actionMatched:copy.actionDifferent)}</p>}</div>{result.evidence.length>0&&<div className="evidence"><label>{t(copy.graph)} {result.graphVerified?'✓':''}</label>{result.evidence.map((e,k)=><p key={k}>{t(e)}</p>)}</div>}</>}<div className="share-actions"><button className="button primary" onClick={()=>{void navigator.clipboard.writeText(shareText).then(()=>setCopied(true)).catch(()=>setError('SERVER_ERROR'));}} disabled={state.persistence!=='ready'}>{t(copied?copy.copied:copy.shareText)}</button><a className="button secondary" href={`https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText)}`} target="_blank" rel="noreferrer">{t(copy.shareX)}</a></div><p className="meta">{t(state.persistence==='ready'?copy.publicNotice:copy.savePending)}</p><ErrorNotice code={error}/></div></div></main>;}
function IngredientRain({state}:{state:PublicState}){const prior=useRef({...state.totals}),[particles,setParticles]=useState<{id:string;icon:string;x:number;delay:number}[]>([]);useEffect(()=>{const added=items.flatMap(i=>Array.from({length:Math.min(4,Math.max(0,state.totals[i.id]-prior.current[i.id]))},(_,k)=>({id:`${state.version}-${i.id}-${k}`,icon:i.icon,x:8+Math.random()*84,delay:Math.random()*.2}))).slice(0,18);prior.current={...state.totals};if(added.length)setParticles(p=>[...p.slice(-12),...added]);},[state.version]);return <div className="ingredient-rain" aria-hidden="true">{particles.map(p=><span key={p.id} style={{left:`${p.x}%`,animationDelay:`${p.delay}s`}}>{p.icon}</span>)}</div>;}
function GameView({state,me,onVote,busy,isStage=false}:{state:PublicState;me:Me|null;onVote?:(kind:'evolution'|'trial',id:string)=>void;busy?:boolean;isStage?:boolean}){const t=useText(),phase=state.phase;
  if(phase==='RESULTS')return <ResultView state={state} result={me?.result||null}/>;
  if(phase==='INTERRUPTED')return <main className="center-state"><Creature egg/><h1>{t(copy.interrupted)}</h1><p>{t(copy.interruptedBody)}</p><a className="button secondary" href="/">{t(copy.back)}</a></main>;
  if(['REVEAL','EVOLUTION_VOTE'].includes(phase))return <main className="wide"><div className="section-heading with-timer"><div><p className="eyebrow">{t(phase==='REVEAL'?copy.reveal:copy.voteHelp)}</p><h1>{t(copy.choose)}</h1></div><Timer state={state}/></div><CandidateCards state={state} me={me} onVote={phase==='EVOLUTION_VOTE'&&onVote?id=>onVote('evolution',id):undefined} busy={busy}/><p className="vote-count">{state.voteCount} / {state.participantCount} {t(copy.votes)} {me?.evolutionVote&&` · ${t(copy.voted)}`}</p></main>;
  if(phase==='TRIAL_VOTE')return <main className="wide trial-view"><div className="section-heading with-timer"><div><p className="eyebrow">{t(copy.voteHelp)}</p><h1>{t(copy.trialTitle)}</h1><p>{t(copy.trialBody)}</p></div><Timer state={state}/></div><div className="trial-scene"><div className="gate">✧</div><Creature candidate={state.winner}/></div><div className="action-grid">{actions.map(a=><button key={a.id} className={`action-card ${me?.trialVote===a.id?'voted':''}`} disabled={!onVote||!!me?.trialVote||busy} onClick={()=>onVote?.('trial',a.id)}><span>{a.icon}</span><h2>{t(a.name)}</h2><p>{t(a.description)}</p><small>{t(me?.trialVote===a.id?copy.chosen:copy.actionVote)}</small></button>)}</div><p className="vote-count">{state.trialVoteCount} / {state.participantCount} {t(copy.votes)}</p></main>;
  if(phase==='BIRTH'||phase==='OUTCOME')return <main className="center-state celebration"><p className="eyebrow">{t(phase==='BIRTH'?copy.born:copy.outcome)}</p><h1>{state.winner&&t(state.winner.name)}</h1><Creature candidate={state.winner} large/>{state.outcome?<blockquote>{t(state.outcome.text)}</blockquote>:<p>{t(state.voteCount===0?copy.noVotesBirth:copy.bornBody)}</p>}<Timer state={state}/></main>;
  if(phase==='GENERATING')return <main className="generation"><div className="section-heading"><p className="eyebrow">✳ HATCH LAB</p><h1>{t(copy.generating)}</h1><p>{t(copy.genBody)}</p></div><div className="graph-scene"><div className="graph-center">✳</div>{items.filter(i=>state.totals[i.id]>0).map((i,k)=><div className={`graph-node n${k}`} key={i.id} style={{'--item-color':i.color} as React.CSSProperties}><span>{i.icon}</span><b>{t(i.name)}</b><small>{state.totals[i.id]}</small></div>)}</div><div className="generation-progress"><span className="pulse-bar"/>{state.generation.ready} / 3 {t(copy.readyImages)}</div><Timer state={state}/></main>;
  return <main className="stage-layout"><div className="stage-main">{phase==='FEEDING'&&<IngredientRain state={state}/>}<div className="section-heading"><p className="eyebrow">{t(copy.live)}</p><h1>{t(phase==='LOBBY'?copy.waiting:phase==='COUNTDOWN'?copy.getReady:phase==='DRAINING'?copy.lastBatch:copy.feedTitle)}</h1></div><Creature egg large/>{phase==='COUNTDOWN'?<div className="countdown-overlay"><Timer state={state}/></div>:<Timer state={state}/>}<Facts state={state}/></div><aside className="stage-aside">{phase==='LOBBY'?<><QR url={state.joinUrl}/><p>{t(copy.lobbyBody)}</p><a href={`/play/${state.id}`} className="button primary">{t(copy.play)}</a></>:<><p className="eyebrow">{t(copy.allIngredients)}</p><IngredientBar state={state}/>{state.mutations.map(m=><div className="mutation-note" key={m.id}>✧ {t(m.name)}</div>)}</>}</aside></main>;
}
function TapPanel({state,me,token}:{state:PublicState;me:Me;token:string}){const t=useText(),item=itemById(me.itemId),[total,setTotal]=useState(me.lastClientTotal),[accepted,setAccepted]=useState(me.acceptedTotal),[rejected,setRejected]=useState(me.lastClientTotal-me.acceptedTotal),[error,setError]=useState('');
  const buffer=useRef({total:me.lastClientTotal,seq:me.lastSeq,ack:me.lastClientTotal,pending:null as null|{roundId:'round-1';seq:number;clientTotal:number},sending:false,closed:false});const phase=useRef(state.phase);phase.current=state.phase;
  useEffect(()=>{let alive=true;async function flush(){const b=buffer.current;if(b.sending||b.closed||(!b.pending&&b.total<=b.ack))return;if(!['FEEDING','DRAINING'].includes(phase.current)){b.closed=true;return;}b.pending??={roundId:'round-1',seq:b.seq+1,clientTotal:b.total};b.sending=true;try{const ack=await api<any>(`/sessions/${state.id}/taps`,b.pending,token);b.seq=ack.ackSeq;b.ack=ack.lastClientTotal;b.pending=null;if(alive){setAccepted(ack.acceptedTotal);setRejected(ack.rejectedTotal);setError('');}}catch(e){if(alive)setError((e as APIError).code);if((e as APIError).code==='PHASE_CLOSED')b.closed=true;}finally{b.sending=false;}}
    const interval=setInterval(()=>void flush(),500);void flush();return()=>{alive=false;clearInterval(interval);};},[state.id,token]);
  function tap(){if(phase.current!=='FEEDING'||buffer.current.total>=10000)return;buffer.current.total++;setTotal(buffer.current.total);}
  return <main className="tap-screen"><div className="section-heading with-timer"><div><p className="eyebrow">{t(copy.yourRole)}</p><h1>{t(item.name)}</h1><p>{t(item.role)}</p></div><Timer state={state}/></div><button className="feed-button" style={{'--item-color':item.color} as React.CSSProperties} disabled={state.phase!=='FEEDING'} onClick={tap}><span>{item.icon}</span><strong>{t(state.phase==='DRAINING'?copy.lastBatch:copy.tap)}</strong><small>{t(item.name)} +1</small></button><div className="tap-count"><strong>{accepted}</strong><span>{t(copy.accepted)}</span>{total>accepted+rejected&&<small>+{total-accepted-rejected} {t(copy.pending)}</small>}</div>{rejected>0&&<p className="meta">{t(copy.rest)}</p>}<ErrorNotice code={error}/><div className="mini-room"><span>{item.icon} {t(item.name)}</span><strong>{state.totals[item.id]}</strong><span>{state.totalAccepted} {t(copy.feeds)}</span></div></main>;
}
function Play({sid}:{sid:string}){const t=useText(),[token,setToken]=useState(()=>localStorage.getItem(`hatch:${sid}:token`)||''),[busy,setBusy]=useState(false),[error,setError]=useState('');const {state,me,error:pollError}=useSession(sid,token);
  async function enter(){setBusy(true);try{const key=`hatch:${sid}:join`,joinRequestId=localStorage.getItem(key)||crypto.randomUUID();localStorage.setItem(key,joinRequestId);const r=await api(`/sessions/${sid}/join`,{joinRequestId});localStorage.setItem(`hatch:${sid}:token`,r.token);setToken(r.token);setError('');}catch(e){setError((e as APIError).code);}finally{setBusy(false);}}
  async function cast(kind:'evolution'|'trial',targetId:string){setBusy(true);try{await api(`/sessions/${sid}/votes/${kind}`,{targetId},token);setError('');}catch(e){setError((e as APIError).code);}finally{setBusy(false);}}
  if(!state)return <Loading error={pollError}/>;
  const role=me?itemById(me.itemId):null;return <><ErrorNotice code={error||pollError}/>{!token&&state.phase==='LOBBY'?<main className="join-screen"><Creature egg/><p className="eyebrow">{t(copy.chooseRole)}</p><h1>{t(copy.homeTitle)}</h1><p>{t(copy.homeBody)}</p><button className="button primary" onClick={()=>void enter()} disabled={busy}>{t(copy.join)}</button><p className="meta">{state.participantCount} {t(copy.players)}</p></main>:me&&state.phase==='LOBBY'?<main className="join-screen role-screen"><div className="role-icon" style={{background:`${role!.color}22`}}>{role!.icon}</div><p className="eyebrow">{t(copy.yourRole)}</p><h1>{t(role!.name)}</h1><p>{t(role!.role)}</p><div className="notice">{t(copy.waitHost)}</div><p className="meta">{t(me.displayName)}</p></main>:me&&['FEEDING','DRAINING'].includes(state.phase)?<TapPanel state={state} me={me} token={token}/>:<>{!token&&!['RESULTS','INTERRUPTED'].includes(state.phase)&&<div className="notice spectator">{t(copy.spectator)} {t(copy.spectatorBody)}</div>}<GameView state={state} me={me} onVote={me?cast:undefined} busy={busy}/></>}</>;}
function Loading({error=''}:{error?:string}){const t=useText();return <main className="center-state"><span className="loading-mark">✳</span><p>{t(copy.loading)}</p><ErrorNotice code={error}/></main>;}
function Stage({sid}:{sid:string}){const {state,error}=useSession(sid,'',true);return state?<><ErrorNotice code={error}/><GameView state={state} me={null} isStage/></>:<Loading error={error}/>;}
function Host(){const t=useText(),[key,setKey]=useState(()=>sessionStorage.getItem('hatch:host')||''),[input,setInput]=useState(''),[health,setHealth]=useState<any>(null),[error,setError]=useState(''),[trial,setTrial]=useState(true),[busy,setBusy]=useState(false),[sid,setSid]=useState(()=>new URLSearchParams(location.search).get('session')||''),[copied,setCopied]=useState(false);const {state}=useSession(sid,'');
  useEffect(()=>{if(!key)void api('/local-host',{}).then(r=>{sessionStorage.setItem('hatch:host',r.token);setKey(r.token);}).catch(()=>{});},[]);
  useEffect(()=>{if(!key)return;let alive=true;async function check(){try{const r=await api('/host/health',undefined,key);if(alive){setHealth(r);setError('');}}catch(e){if(alive)setError((e as APIError).code);}}void check();const timer=setInterval(check,5000);return()=>{alive=false;clearInterval(timer);};},[key]);
  async function create(){setBusy(true);try{const s=await api<PublicState>('/sessions',{commandId:crypto.randomUUID(),enableTrial:trial},key);setSid(s.id);history.replaceState(null,'',`/host?session=${s.id}`);setError('');}catch(e){setError((e as APIError).code);}finally{setBusy(false);}}
  async function command(type:string){if(!state)return;setBusy(true);try{await api(`/sessions/${state.id}/commands`,{type,commandId:crypto.randomUUID(),expectedPhaseRevision:state.phaseRevision},key);setError('');}catch(e){setError((e as APIError).code);}finally{setBusy(false);}}
  return <main className="host-page"><div className="section-heading"><p className="eyebrow">HATCH LAB</p><h1>{t(copy.host)}</h1></div><ErrorNotice code={error}/>{!health?<form className="host-auth" onSubmit={e=>{e.preventDefault();sessionStorage.setItem('hatch:host',input);setKey(input);}}><label htmlFor="host-secret">{t(copy.hostKey)}</label><input id="host-secret" type="password" value={input} onChange={e=>setInput(e.target.value)} autoComplete="off"/><p>{t(copy.hostHint)}</p><button className="button primary">{t(copy.unlock)}</button></form>:<><div className="connection-row"><span>Neo4j · {t(health.graph==='ready'?copy.ready:health.graph==='disabled'?copy.disabled:copy.pendingStatus)}</span><span>GPU · {t(health.gpu==='fallback'?copy.localFallback:health.gpu==='configured'?copy.configured:copy.disabled)}</span></div>{!state||['RESULTS','INTERRUPTED'].includes(state.phase)?<div className="host-start"><Creature egg/><label className="check"><input type="checkbox" checked={trial} onChange={e=>setTrial(e.target.checked)}/>{t(copy.trial)}</label><button className="button primary" disabled={busy} onClick={()=>void create()}>{t(state?copy.newRoom:copy.create)}</button>{health.sessions.filter((s:any)=>!['RESULTS','INTERRUPTED'].includes(s.phase)).map((s:any)=><a className="button secondary" key={s.id} href={`/host?session=${s.id}`}>{t(copy.room)} {s.id.slice(0,6)} · {s.participants} {t(copy.players)}</a>)}</div>:<div className="host-room"><div><span className="capsule">{t(copy.room)} {state.id.slice(0,6).toUpperCase()}</span><h2>{state.participantCount} {t(copy.players)}</h2><QR url={state.joinUrl}/><div className="host-actions"><a className="button secondary" href={state.stageUrl} target="_blank" rel="noreferrer">{t(copy.stage)} ↗</a><a className="button secondary" href={state.joinUrl} target="_blank" rel="noreferrer">{t(copy.play)} ↗</a><button className="button secondary" onClick={()=>void navigator.clipboard.writeText(state.joinUrl).then(()=>setCopied(true)).catch(()=>setError('SERVER_ERROR'))}>{t(copied?copy.copied:copy.copyLink)}</button></div></div><div className="host-control"><Timer state={state}/><Facts state={state}/><IngredientBar state={state}/>{state.phase==='LOBBY'&&<button className="button primary" onClick={()=>void command('start')} disabled={busy||!state.participantCount}>{t(copy.start)}</button>}{state.phase==='GENERATING'&&<button className="button secondary" onClick={()=>void command('use-fallback')} disabled={busy}>{t(copy.fallback)}</button>}<button className="text-button danger" onClick={()=>void command('interrupt')} disabled={busy}>{t(copy.stop)}</button></div></div>}</>}</main>;}
function Shared({shareId}:{shareId:string}){const [data,setData]=useState<{result:PersonalResult;state:PublicState}|null>(null),[error,setError]=useState('');useEffect(()=>{void api(`/shared-results/${shareId}`).then(setData).catch(e=>setError(e.code));},[shareId]);return data?<ResultView {...data}/>:<Loading error={error}/>;}
function App(){const [lang,setLang]=useState<Lang>(()=>localStorage.getItem('hatch:language')==='ja'?'ja':'en');useEffect(()=>{localStorage.setItem('hatch:language',lang);document.documentElement.lang=lang;document.title=lang==='en'?'HATCH — Crowd Monster':'HATCH — みんなの怪物';},[lang]);const [,route,sid]=location.pathname.split('/');return <Locale.Provider value={{lang,setLang}}><Header/>{route==='host'?<Host/>:route==='play'&&sid?<Play sid={sid}/>:['stage','monster'].includes(route)&&sid?<Stage sid={sid}/>:route==='r'&&sid?<Shared shareId={sid}/>:<Home/>}<footer><span>HATCH / 2026</span><span>{copy.tag[lang]}</span></footer></Locale.Provider>;}
createRoot(document.getElementById('root')!).render(<App/>);
